-- Select all data print

SELECT * 
FROM SCOTT.EMP;


-- Print ALL EMPLOY

SELECT ENAME 
FROM SCOTT.EMP;


-- Print ALL JOB WITH NAME

SELECT ENAME ,JOB
FROM SCOTT.EMP;

-- PRINT ALL TABLE column (EMP TABLE)

SELECT * 
FROM SCOTT.EMP;

-- PRINT ALL TABLE column (DEPT TABLE)

SELECT * 
FROM SCOTT.DEPT;


-- Print ALL employee NO , employee NAME ,JOB,MANAGER ,HIREDATE ,COMM,DEPTNO

SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,COMM,DEPTNO
FROM SCOTT.EMP;